-- The name of the author will be found by doing a SQL query using the user_id of author and the user profile table.
create table preset (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  name character varying not null check (char_length(btrim(name)) > 0), -- Checks to make sure title is at least 1 character long
  description character varying,
  scene_data json not null,
  thumbnail_url text,
  likes bigint not null default 0,
  constraint preset_pkey primary key (id),
  constraint preset_uid_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

-- Enables RLS on table to control how users add/modify preset.
ALTER TABLE preset ENABLE ROW LEVEL SECURITY;

-- The following settings allow users to select anything, but they can only modify/add their own preset.
CREATE POLICY "Allow public read" ON preset
  FOR SELECT USING (true);

CREATE POLICY "Allow users to insert their own preset" ON preset
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own preset" ON preset
  FOR UPDATE USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own preset" ON preset
  FOR DELETE USING (auth.uid() = user_id);


